### ISSUE TITLE
Installation Issue on Travis-CI  (What am I doing wrong...?)

### ISSUE THREAD

**Issue by nelsonic** [redis/hiredis-node#107]
Hi Redis Team,

We have an app that uses Redis (and `hiredis-node` *specifically*)
But for some reason the build is no longer working on Travis-CI

The NPM Debug Log says:  

```sh
npm ERR! Failed at the hiredis@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
```

see: https://travis-ci.org/dwyl/hapi-socketio-redis-chat-example/builds/89435791#L2177

<img width="904" alt="hiredis-node-fails-to-install" src="https://cloud.githubusercontent.com/assets/194400/10969693/e105b94c-83c1-11e5-9631-5e2353877c8a.png">

Could you *please* give me some guidance on what I am doing wrong? *thanks*!

**Comment by badboy** [comment]
Use a newer gcc. From our [`.travis.yml`](https://github.com/redis/hiredis-node/blob/master/.travis.yml#L3-L10):

```yaml
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
```
